import { NextResponse } from "next/server";

export async function GET() {
  return NextResponse.json({
    config: {
      enable_signup: true,
      is_google_enabled: false,
      is_github_enabled: false,
      is_gitlab_enabled: false,
      is_magic_login_enabled: false,
      is_email_password_enabled: true,
      github_app_name: "",
      slack_client_id: null,
      posthog_api_key: null,
      posthog_host: null,
      has_unsplash_configured: false,
      has_openai_configured: false,
      file_size_limit: 5242880,
      is_smtp_configured: false,
      is_intercom_enabled: true,
      intercom_app_id: "",
      admin_base_url: null,
      space_base_url: null,
      app_base_url: null,
    },
    instance: {
      id: "27b46ffb-1b46-477e-b6e2-da9efdac00c7",
      created_at: "2024-11-23T15:36:31.779064Z",
      updated_at: "2024-11-23T15:39:30.942682Z",
      deleted_at: null,
      instance_name: "tidvn",
      whitelist_emails: null,
      instance_id: "5f6839f026b58adb6e9474ad",
      current_version: "0.23.1",
      latest_version: "0.23.1",
      product: "plane-ce",
      domain: "",
      last_checked_at: "2024-11-23T15:36:31.773527Z",
      namespace: null,
      is_telemetry_enabled: false,
      is_support_required: true,
      is_setup_done: true,
      is_signup_screen_visited: false,
      is_verified: false,
      created_by: null,
      updated_by: "77d86ba1-93ca-4d4f-b07d-2f5219eedd65",
      workspaces_exist: true,
    },
  });
}
